CREATE DATABASE starrdb;

CREATE TABLE starrs(
    id INT (9)UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    fname VARCHAR(50)  NOT NULL,
    lname VARCHAR(50)  NOT NULL,
    email VARCHAR(50) NOT NULL,
    pass VARCHAR(50)  NOT NULL,
    reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 

);